"""create initial tables

Revision ID: 03dcb81a88b3
Revises: 
Create Date: 2025-04-27 15:57:38.338133

"""
from typing import Sequence, Union
import sqlmodel

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03dcb81a88b3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('last_user_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_group_id', sa.Integer(), nullable=False),
    sa.Column('telegram_user_id', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_last_user_message_telegram_group_id'), 'last_user_message', ['telegram_group_id'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_user_id', sa.Integer(), nullable=False),
    sa.Column('telegram_group_id', sa.Integer(), nullable=False),
    sa.Column('currency_balance', sa.Integer(), nullable=False),
    sa.Column('letter_limits_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('consecutive_message_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_user_id', 'telegram_group_id', name='uq_user_group')
    )
    op.create_index(op.f('ix_user_telegram_group_id'), 'user', ['telegram_group_id'], unique=False)
    op.create_index(op.f('ix_user_telegram_user_id'), 'user', ['telegram_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_telegram_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_telegram_group_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_last_user_message_telegram_group_id'), table_name='last_user_message')
    op.drop_table('last_user_message')
    # ### end Alembic commands ###
