"""Initial database schema

Revision ID: 5a9f64bd3495
Revises: 
Create Date: 2025-04-27 01:58:59.733651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a9f64bd3495'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_user_id', sa.Integer(), nullable=False),
    sa.Column('currency_balance', sa.Integer(), nullable=False),
    sa.Column('letter_limits_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_valid_messages_sent', sa.Integer(), nullable=False),
    sa.Column('last_message_timestamp', sa.Float(), nullable=True),
    sa.Column('consecutive_message_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_telegram_user_id'), 'user', ['telegram_user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_telegram_user_id'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
