"""small fixes

Revision ID: 647b832a6763
Revises: bb63baa3d5d7
Create Date: 2025-04-27 17:39:24.366407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '647b832a6763'
down_revision: Union[str, None] = 'bb63baa3d5d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'consecutive_message_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('consecutive_message_count', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###
