"""add lootbox table

Revision ID: 9ab764df24b0
Revises: 647b832a6763
Create Date: 2025-05-05 21:19:41.944041

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9ab764df24b0"
down_revision: Union[str, None] = "647b832a6763"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lootbox",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("telegram_user_id", sa.Integer(), nullable=False),
        sa.Column("telegram_group_id", sa.Integer(), nullable=False),
        sa.Column("rarity", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("opened", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("lootbox")
    # ### end Alembic commands ###
