"""add number of messages

Revision ID: bb63baa3d5d7
Revises: 03dcb81a88b3
Create Date: 2025-04-27 17:16:08.511151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb63baa3d5d7'
down_revision: Union[str, None] = '03dcb81a88b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('number_of_messages_sent', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'number_of_messages_sent')
    # ### end Alembic commands ###
